version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
